<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cellnames [
<!ELEMENT cell ((de, en?) | (en, de?))>
<!ELEMENT de (#PCDATA)>
<!ELEMENT en (#PCDATA)>
<!ELEMENT cellnames (cell*)>
]>
<cellnames>
  <cell>
    <de>Abaelun-Mine</de>
    <en>Abaelun Mine</en>
  </cell>
  <cell>
    <de>Abaesen-Pulu, Eiermine</de>
    <en>Abaesen-Pulu Egg Mine</en>
  </cell>
  <cell>
    <de>Abanabi</de>
    <en>Abanabi</en>
  </cell>
  <cell>
    <de>Abebaal, Eiermine</de>
    <en>Abebaal Egg Mine</en>
  </cell>
  <cell>
    <de>Abernanit</de>
    <en>Abernanit</en>
  </cell>
  <cell>
    <de>Abinabi</de>
    <en>Abinabi</en>
  </cell>
  <cell>
    <de>Adanumuran</de>
    <en>Adanumuran</en>
  </cell>
  <cell>
    <de>Addadshashanammu, Schrein</de>
    <en>Addadshashanammu, Shrine</en>
  </cell>
  <cell>
    <de>Addamasartus</de>
    <en>Addamasartus</en>
  </cell>
  <cell>
    <de>Ahallaraddon, Eiermine</de>
    <en>Ahallaraddon Egg Mine</en>
  </cell>
  <cell>
    <de>Ahanibi-Malmus, Eiermine</de>
    <en>Ahanibi-Malmus Egg Mine</en>
  </cell>
  <cell>
    <de>Aharasaplit-Lager, Zallays Zelt</de>
    <en>Aharasaplit Camp, Zallay's Yurt</en>
  </cell>
  <cell>
    <de>Aharnabi</de>
    <en>Aharnabi</en>
  </cell>
  <cell>
    <de>Aharunartus</de>
    <en>Aharunartus</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager</de>
    <en>Ahemmusa Camp</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager, Addammus' Zelt</de>
    <en>Ahemmusa Camp, Addammus's Yurt</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager, Assamma-Idans Zelt</de>
    <en>Ahemmusa Camp, Assamma-Idan's Yurt</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager, Dutadalks Zelt</de>
    <en>Ahemmusa Camp, Dutadalk's Yurt</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager, Kausis Zelt</de>
    <en>Ahemmusa Camp, Kausi's Yurt</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager, Lanabis Zelt</de>
    <en>Ahemmusa Camp, Lanabi's Yurt</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager, Mamaeas Zelt</de>
    <en>Ahemmusa Camp, Mamaea's Yurt</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager, Nummus Zelt</de>
    <en>Ahemmusa Camp, Nummu's Yurt</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager, Zelt der Weisen Frau</de>
    <en>Ahemmusa Camp, Wise Woman's Yurt</en>
  </cell>
  <cell>
    <de>Ahemmusa-Lager, Zelt des Ashkhan</de>
    <en>Ahemmusa Camp, Ashkhan's Yurt</en>
  </cell>
  <cell>
    <de>Ahinipalit</de>
    <en>Ahinipalit</en>
  </cell>
  <cell>
    <de>Aidanat-Lager, Abassels Zelt</de>
    <en>Aidanat Camp, Abassel's Yurt</en>
  </cell>
  <cell>
    <de>Ainab</de>
    <en>Ainab</en>
  </cell>
  <cell>
    <de>Ainab, Schrein</de>
    <en>Ainab, Shrine</en>
  </cell>
  <cell>
    <de>Ainat</de>
    <en>Ainat</en>
  </cell>
  <cell>
    <de>Akimaes-Grotte</de>
    <en>Akimaes Grotto</en>
  </cell>
  <cell>
    <de>Akimaes-Ilanipu, Eiermine</de>
    <en>Akimaes-Ilanipu Egg Mine</en>
  </cell>
  <cell>
    <de>Akulakhans Kammer</de>
    <en>Akulakhan's Chamber</en>
  </cell>
  <cell>
    <de>Alas-Ahnengruft</de>
    <en>Alas Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Ald Daedroth</de>
    <en>Ald Daedroth</en>
  </cell>
  <cell>
    <de>Ald Daedroth, Innerer Schrein</de>
    <en>Ald Daedroth, Inner Shrine</en>
  </cell>
  <cell>
    <de>Ald Daedroth, Linker Flügel</de>
    <en>Ald Daedroth, Left Wing</en>
  </cell>
  <cell>
    <de>Ald Daedroth, Rechter Flügel</de>
    <en>Ald Daedroth, Right Wing</en>
  </cell>
  <cell>
    <de>Ald Daedroth, Vorraum</de>
    <en>Ald Daedroth, Antechamber</en>
  </cell>
  <cell>
    <de>Ald Daedroth, Äußerer Schrein</de>
    <en>Ald Daedroth, Outer Shrine</en>
  </cell>
  <cell>
    <de>Ald Redaynia</de>
    <en>Ald Redaynia</en>
  </cell>
  <cell>
    <de>Ald Redaynia, Turm</de>
    <en>Ald Redaynia, Tower</en>
  </cell>
  <cell>
    <de>Ald Sotha</de>
    <en>Ald Sotha</en>
  </cell>
  <cell>
    <de>Ald Sotha, Obere Ebene</de>
    <en>Ald Sotha, Upper Level</en>
  </cell>
  <cell>
    <de>Ald Sotha, Schrein</de>
    <en>Ald Sotha, Shrine</en>
  </cell>
  <cell>
    <de>Ald Sotha, Untere Ebene</de>
    <en>Ald Sotha, Lower Level</en>
  </cell>
  <cell>
    <de>Ald Velothi</de>
    <en>Ald Velothi</en>
  </cell>
  <cell>
    <de>Ald Velothi, Außenposten</de>
    <en>Ald Velothi, Outpost</en>
  </cell>
  <cell>
    <de>Ald Velothi, Fevila Bethranos Hütte</de>
    <en>Ald Velothi, Fevila Bethrano's Shack</en>
  </cell>
  <cell>
    <de>Ald Velothi, Ganus Lloryns Hütte</de>
    <en>Ald Velothi, Ganus Lloryn's Shack</en>
  </cell>
  <cell>
    <de>Ald Velothi, Ienas Arvels Hütte</de>
    <en>Ald Velothi, Ienas Arvel's Shack</en>
  </cell>
  <cell>
    <de>Ald Velothi, Lledsea Relas' Hütte</de>
    <en>Ald Velothi, Lledsea Relas's Shack</en>
  </cell>
  <cell>
    <de>Ald Velothi, Llerar Vindens Hütte</de>
    <en>Ald Velothi, Llerar Vinden's Shack</en>
  </cell>
  <cell>
    <de>Ald Velothi, Sathas Rivuls Hütte</de>
    <en>Ald Velothi, Sathas Rivul's Shack</en>
  </cell>
  <cell>
    <de>Ald Velothi, Vireveri Darethrans Hütte</de>
    <en>Ald Velothi, Vireveri Darethran's Shack</en>
  </cell>
  <cell>
    <de>Ald'ruhn</de>
    <en>Ald-ruhn</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Arobar, Privatquartiere</de>
    <en>Ald-ruhn, Arobar Private Quarters</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Arobar-Wachquartiere</de>
    <en>Ald-ruhn, Arobar Guard Quarters</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Aryni Orethis Haus</de>
    <en>Ald-ruhn, Aryni Orethi's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Bevene Releth: Schneiderin</de>
    <en>Ald-ruhn, Bevene Releth: Clothier</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Bivale Teneran: Schneiderin</de>
    <en>Ald-ruhn, Bivale Teneran: Clothier</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Boldrisa Andranos Haus</de>
    <en>Ald-ruhn, Boldrisa Andrano's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Braynas Hlervus Haus</de>
    <en>Ald-ruhn, Braynas Hlervu's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Cienne Sintieve: Alchemistin</de>
    <en>Ald-ruhn, Cienne Sintieve: Alchemist</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Codus Callonus: Buchhändler</de>
    <en>Ald-ruhn, Codus Callonus: Bookseller</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Dandera Selaro: Schmiedin</de>
    <en>Ald-ruhn, Dandera Selaro: Smith</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Daynes Redothril: Pfandleiher</de>
    <en>Ald-ruhn, Daynes Redothril: Pawnbroker</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Die Ratte und der Topf</de>
    <en>Ald-ruhn, The Rat In The Pot</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Dravasa Andrethis Haus</de>
    <en>Ald-ruhn, Dravasa Andrethi's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Drinar Varyons Haus</de>
    <en>Ald-ruhn, Drinar Varyon's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Eingang zum Haus Arobar</de>
    <en>Ald-ruhn, Arobar Manor Entrance</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Eingang zum Haus Llethri</de>
    <en>Ald-ruhn, Llethri Manor Entrance</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Eingang zum Haus Venim</de>
    <en>Ald-ruhn, Venim Manor Entrance</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Galsa Gindus Haus</de>
    <en>Ald-ruhn, Galsa Gindu's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Galthragoths Haus</de>
    <en>Ald-ruhn, Galthragoth's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Gildans Haus</de>
    <en>Ald-ruhn, Gildan's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Gildehalle der Morag Tong </de>
    <en>Ald-ruhn, Morag Tong Guildhall</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Gindrala Hlerans Haus</de>
    <en>Ald-ruhn, Gindrala Hleran's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Goras Andrelos Haus</de>
    <en>Ald-ruhn, Goras Andrelo's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Guls Llervus Haus</de>
    <en>Ald-ruhn, Guls Llervu's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Hanarai Assutlanipals Haus</de>
    <en>Ald-ruhn, Hanarai Assutlanipal's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Haus Arobar</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Haus Llethri</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Haus Ramoran</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Haus Sarethi</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Haus Venim</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Haus Venim, Privatquartiere</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Haus Venim, rechter Flügel</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Ienas Sarandas' Haus</de>
    <en>Ald-ruhn, Ienas Sarandas's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Ilmirils Haus</de>
    <en>Ald-ruhn, Ilmiril's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Kriegergilde</de>
    <en>Ald-ruhn, Guild of Fighters</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Llether Vari: Verzauberungen</de>
    <en>Ald-ruhn, Llether Vari: Enchanter</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Llethri Wachquartiere</de>
    <en>Ald-ruhn, Llethri Guard Quarters</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Llethri, Privatquartiere</de>
    <en>Ald-ruhn, Llethri Private Quarters</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Magiergilde</de>
    <en>Ald-ruhn, Guild of Mages</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Malpenix Blonia: Händler</de>
    <en>Ald-ruhn, Malpenix Blonia: Trader</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Morvayn-Quartiere</de>
    <en>Ald-ruhn, Morvayn Quarters</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Pellecia Aurrus' Haus</de>
    <en>Ald-ruhn, Pellecia Aurrus's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Ramoran, Privatquartiere</de>
    <en>Ald-ruhn, Ramoran Private Quarters</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Ratsherberge</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Ratstaverne</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Redoranische Ratshalle</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Sarethi-Wachquartiere</de>
    <en>Ald-ruhn, Sarethi Guard Quarters</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Tauryons Haus</de>
    <en>Ald-ruhn, Tauryon's House</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Taverne Ald Skar</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Tempel</de>
    <en>Ald-ruhn, Temple</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Tiras Sadus: Händler</de>
    <en>Ald-ruhn, Tiras Sadus: General Merchandise</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Tuveso Beleth: Schmiedin</de>
    <en>Ald-ruhn, Tuveso Beleth: Smith</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Venim-Wachquartiere</de>
    <en>Ald-ruhn, Venim Manor Guard Quarters</en>
  </cell>
  <cell>
    <de>Ald'ruhn, Wachturm 1</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Wachturm 2</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Wohndistrikt</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Zugang zum Redoranischen Rat</de>
  </cell>
  <cell>
    <de>Ald'ruhn, Übungsraum</de>
    <en>Ald-ruhn, Practice Room</en>
  </cell>
  <cell>
    <de>Aleft</de>
    <en>Aleft</en>
  </cell>
  <cell>
    <de>Alen-Ahnengruft</de>
    <en>Alen Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Almurbalarammi, Schrein</de>
    <en>Almurbalarammi, Shrine</en>
  </cell>
  <cell>
    <de>Alofs Bauernhaus</de>
    <en>Alof's Farmhouse</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Basar-Abwasserkanäle</de>
    <en>Old Mournhold: Bazaar Sewers</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Gedna Relvels Grab</de>
    <en>Old Mournhold: Gedna Relvel's Tomb</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Haus Moril, Hof</de>
    <en>Old Mournhold: Moril Manor, Courtyard</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Haus Moril, Nordgebäude</de>
    <en>Old Mournhold: Moril Manor, North Building</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Haus Moril, Ostgebäude</de>
    <en>Old Mournhold: Moril Manor, East Building</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Häuser-Abwasserkanäle</de>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Häuser-Distrikt</de>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Häuserruinen</de>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Palastkanäle</de>
    <en>Old Mournhold: Palace Sewers</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Schlachtfeld</de>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Stadttor</de>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Tempelgruft</de>
    <en>Old Mournhold: Temple Crypt</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Tempelgärten</de>
    <en>Old Mournhold: Temple Gardens</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Tempelkanäle</de>
    <en>Old Mournhold: Temple Sewers</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Tempelkanäle Ost</de>
    <en>Old Mournhold: Temple Sewers East</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Tempelkanäle West</de>
    <en>Old Mournhold: Temple Sewers West</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Tempelkatakomben</de>
    <en>Old Mournhold: Temple Catacombs</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Tempelschrein</de>
    <en>Old Mournhold: Temple Shrine</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Teran-Halle</de>
    <en>Old Mournhold: Teran Hall</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Teran-Halle, Ostgebäude</de>
    <en>Old Mournhold: Teran Hall, East Bldg</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Tränen von Amun-Shae</de>
    <en>Old Mournhold: Tears of Amun-Shae</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Verlassene Gruft</de>
    <en>Old Mournhold: Abandoned Crypt</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Verlassene Kanäle</de>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Verlassener Gang</de>
  </cell>
  <cell>
    <de>Alt-Gramfeste: Waffenkammer-Ruinen</de>
    <en>Old Mournhold: Armory Ruins</en>
  </cell>
  <cell>
    <de>Alt-Gramfeste: West-Kanäle</de>
    <en>Old Mournhold: West Sewers</en>
  </cell>
  <cell>
    <de>Altes Schiffswrack, Kabine</de>
  </cell>
  <cell>
    <de>Altes Schiffswrack, Oberdeck</de>
  </cell>
  <cell>
    <de>Altes Schiffswrack, Unterdeck</de>
  </cell>
  <cell>
    <de>Andalen-Ahnengruft</de>
    <en>Andalen Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Andalor-Ahnengruft</de>
    <en>Andalor Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Andas-Ahnengruft</de>
    <en>Andas Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Andasreth</de>
    <en>Andasreth</en>
  </cell>
  <cell>
    <de>Andasreth, Obere Ebene</de>
    <en>Andasreth, Upper Level</en>
  </cell>
  <cell>
    <de>Andasreth, Propylon-Kammer</de>
    <en>Andasreth, Propylon Chamber</en>
  </cell>
  <cell>
    <de>Andasreth, Untere Ebene</de>
    <en>Andasreth, Lower Level</en>
  </cell>
  <cell>
    <de>Andavel-Ahnengruft</de>
    <en>Andavel Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Andrano-Ahnengruft</de>
    <en>Andrano Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Andrethi-Ahnengruft</de>
    <en>Andrethi Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Andules-Ahnengruft</de>
    <en>Andules Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Ansi</de>
    <en>Ansi</en>
  </cell>
  <cell>
    <de>Aralen-Ahnengruft</de>
    <en>Aralen Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Aran-Ahnengruft</de>
    <en>Aran Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Arano-Ahnengruft</de>
    <en>Arano Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Arano-Plantage</de>
    <en>Arano Plantation</en>
  </cell>
  <cell>
    <de>Arenim-Ahnengruft</de>
    <en>Arenim Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Arethan-Ahnengruft</de>
    <en>Arethan Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Arkngthand, Halle der Zentrifuge</de>
    <en>Arkngthand, Hall of Centrifuge</en>
  </cell>
  <cell>
    <de>Arkngthand, Himmelsgalerie</de>
    <en>Arkngthand, Heaven's Gallery</en>
  </cell>
  <cell>
    <de>Arkngthand, Klageläuten-Halle</de>
    <en>Arkngthand, Weepingbell Hall</en>
  </cell>
  <cell>
    <de>Arkngthand, Landblutgalerie</de>
    <en>Arkngthand, Land's Blood Gallery</en>
  </cell>
  <cell>
    <de>Arkngthand, Tiefe Erzpassage</de>
    <en>Arkngthand, Deep Ore Passage</en>
  </cell>
  <cell>
    <de>Arkngthand, Zellen der Hohlen Hand</de>
    <en>Arkngthand, Cells of Hollow Hand</en>
  </cell>
  <cell>
    <de>Arkngthunch-Sturdumz</de>
    <en>Arkngthunch-Sturdumz</en>
  </cell>
  <cell>
    <de>Arvel-Plantage</de>
    <en>Arvel Plantation</en>
  </cell>
  <cell>
    <de>Aryon-Ahnengruft</de>
    <en>Aryon Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Arys-Ahnengruft</de>
    <en>Arys Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Asha-Ahhe, Eiermine</de>
    <en>Asha-Ahhe Egg Mine</en>
  </cell>
  <cell>
    <de>Ashalmawia</de>
    <en>Ashalmawia</en>
  </cell>
  <cell>
    <de>Ashalmawia, Schrein</de>
    <en>Ashalmawia, Shrine</en>
  </cell>
  <cell>
    <de>Ashalmawia, Schrein, Versunkene Gewölbe</de>
    <en>Ashalmawia, Shrine, Sunken Vaults</en>
  </cell>
  <cell>
    <de>Ashalmimilkala, Schrein</de>
    <en>Ashalmimilkala, Shrine</en>
  </cell>
  <cell>
    <de>Ashamanu-Lager, Kaushas Zelt</de>
    <en>Ashamanu Camp, Kausha's Yurt</en>
  </cell>
  <cell>
    <de>Ashanammu</de>
    <en>Ashanammu</en>
  </cell>
  <cell>
    <de>Ashimanu, Eiermine</de>
    <en>Ashimanu Egg Mine</en>
  </cell>
  <cell>
    <de>Ashimanu, Eiermine, Nest der Königin</de>
    <en>Ashimanu Egg Mine, Queen's Lair</en>
  </cell>
  <cell>
    <de>Ashinabi</de>
    <en>Ashinabi</en>
  </cell>
  <cell>
    <de>Ashinabi, Schmugglerhöhle</de>
    <en>Ashinabi, Smuggler Den</en>
  </cell>
  <cell>
    <de>Ashir-Dan</de>
    <en>Ashir-Dan</en>
  </cell>
  <cell>
    <de>Ashirbadon</de>
    <en>Ashirbadon</en>
  </cell>
  <cell>
    <de>Ashmelech</de>
    <en>Ashmelech</en>
  </cell>
  <cell>
    <de>Ashunartes, Schrein</de>
    <en>Ashunartes, Shrine</en>
  </cell>
  <cell>
    <de>Ashurnabitashpi</de>
    <en>Ashurnabitashpi</en>
  </cell>
  <cell>
    <de>Ashurnibibi</de>
    <en>Ashurnibibi</en>
  </cell>
  <cell>
    <de>Ashurnibibi, Schrein</de>
    <en>Ashurnibibi, Shrine</en>
  </cell>
  <cell>
    <de>Assalkushalit, Schrein</de>
    <en>Assalkushalit, Shrine</en>
  </cell>
  <cell>
    <de>Assarnatamat, Schrein</de>
    <en>Assarnatamat, Shrine</en>
  </cell>
  <cell>
    <de>Assarnibibiberg</de>
  </cell>
  <cell>
    <de>Assarnud</de>
    <en>Assarnud</en>
  </cell>
  <cell>
    <de>Assemanu</de>
    <en>Assemanu</en>
  </cell>
  <cell>
    <de>Assemanu, Schrein</de>
    <en>Assemanu, Shrine</en>
  </cell>
  <cell>
    <de>Assernerairan, Schrein</de>
    <en>Assernerairan, Shrine</en>
  </cell>
  <cell>
    <de>Assu</de>
    <en>Assu</en>
  </cell>
  <cell>
    <de>Assumanu</de>
    <en>Assumanu</en>
  </cell>
  <cell>
    <de>Assurdirapal, Innerer Schrein</de>
    <en>Assurdirapal, Inner Shrine</en>
  </cell>
  <cell>
    <de>Assurdirapal, Schrein</de>
    <en>Assurdirapal, Shrine</en>
  </cell>
  <cell>
    <de>Assurnabitashpi</de>
    <en>Assurnabitashpi</en>
  </cell>
  <cell>
    <de>Assurnabitashpi, Schrein</de>
    <en>Assurnabitashpi, Shrine</en>
  </cell>
  <cell>
    <de>Aufgegebenes Schiffswrack, Kabine</de>
  </cell>
  <cell>
    <de>Aufgegebenes Schiffswrack, Oberdeck</de>
  </cell>
  <cell>
    <de>Aufgegebenes Schiffswrack, Unterdeck</de>
  </cell>
  <cell>
    <de>Azuras Schrein</de>
  </cell>
  <cell>
    <de>Bal Fell</de>
    <en>Bal Fell</en>
  </cell>
  <cell>
    <de>Bal Fell, Innerer Schrein</de>
    <en>Bal Fell, Inner Shrine</en>
  </cell>
  <cell>
    <de>Bal Fell, Westlicher Flügel</de>
    <en>Bal Fell, West Wing</en>
  </cell>
  <cell>
    <de>Bal Fell, Äußerer Schrein</de>
    <en>Bal Fell, Outer Shrine</en>
  </cell>
  <cell>
    <de>Bal Fell, Östlicher Flügel</de>
    <en>Bal Fell, East Wing</en>
  </cell>
  <cell>
    <de>Bal Isra</de>
    <en>Bal Isra</en>
  </cell>
  <cell>
    <de>Bal Ur</de>
    <en>Bal Ur</en>
  </cell>
  <cell>
    <de>Bal Ur, Schrein</de>
    <en>Bal Ur, Shrine</en>
  </cell>
  <cell>
    <de>Bal Ur, Untergrund</de>
    <en>Bal Ur, Underground</en>
  </cell>
  <cell>
    <de>Balmora</de>
    <en>Balmora</en>
  </cell>
  <cell>
    <de>Balmora, Acht Teller</de>
    <en>Balmora, Eight Plates</en>
  </cell>
  <cell>
    <de>Balmora, Astius Hanotepelus' Haus</de>
    <en>Balmora, Astius Hanotepelus' House</en>
  </cell>
  <cell>
    <de>Balmora, Balyn Omarels Haus</de>
    <en>Balmora, Balyn Omarel's House</en>
  </cell>
  <cell>
    <de>Balmora, Caius Cosades Haus</de>
    <en>Balmora, Caius Cosades' House</en>
  </cell>
  <cell>
    <de>Balmora, Clagius Clanler: Händler</de>
    <en>Balmora, Clagius Clanler: Outfitter</en>
  </cell>
  <cell>
    <de>Balmora, Die Klingengrube</de>
  </cell>
  <cell>
    <de>Balmora, Dorisa Darvel: Buchhändlerin</de>
    <en>Balmora, Dorisa Darvel: Bookseller</en>
  </cell>
  <cell>
    <de>Balmora, Dralasa Nithryon: Pfandleiherin</de>
    <en>Balmora, Dralasa Nithryon: Pawnbroker</en>
  </cell>
  <cell>
    <de>Balmora, Dralcea Arethis Haus</de>
    <en>Balmora, Dralcea Arethi's House</en>
  </cell>
  <cell>
    <de>Balmora, Dralosa Athrens Haus</de>
    <en>Balmora, Dralosa Athren's House</en>
  </cell>
  <cell>
    <de>Balmora, Drarayne Thelas Haus</de>
    <en>Balmora, Drarayne Thelas' House</en>
  </cell>
  <cell>
    <de>Balmora, Drarayne Thelas Lager</de>
    <en>Balmora, Drarayne Thelas' Storage</en>
  </cell>
  <cell>
    <de>Balmora, Dura gra-Bol's Haus</de>
    <en>Balmora, Dura gra-Bol's House</en>
  </cell>
  <cell>
    <de>Balmora, Flinkfinger-Eddis Haus</de>
    <en>Balmora, Fast Eddie's House</en>
  </cell>
  <cell>
    <de>Balmora, Haus Hlaalo</de>
    <en>Balmora, Hlaalo Manor</en>
  </cell>
  <cell>
    <de>Balmora, Haus Nerano</de>
    <en>Balmora, Nerano Manor</en>
  </cell>
  <cell>
    <de>Balmora, Haus Tyravel</de>
    <en>Balmora, Tyravel Manor</en>
  </cell>
  <cell>
    <de>Balmora, Haus des Hlaalu-Rates</de>
  </cell>
  <cell>
    <de>Balmora, Hecerindes Haus</de>
    <en>Balmora, Hecerinde's House</en>
  </cell>
  <cell>
    <de>Balmora, Itans Haus</de>
    <en>Balmora, Itan's House</en>
  </cell>
  <cell>
    <de>Balmora, Karlirahs Haus</de>
    <en>Balmora, Karlirah's House</en>
  </cell>
  <cell>
    <de>Balmora, Kriegergilde</de>
    <en>Balmora, Guild of Fighters</en>
  </cell>
  <cell>
    <de>Balmora, Magiergilde</de>
    <en>Balmora, Guild of Mages</en>
  </cell>
  <cell>
    <de>Balmora, Meldor: Waffenschmied</de>
    <en>Balmora, Meldor: Armorer</en>
  </cell>
  <cell>
    <de>Balmora, Milie Hastien: Schneiderin</de>
    <en>Balmora, Milie Hastien: Fine Clothier</en>
  </cell>
  <cell>
    <de>Balmora, Morag Tong, Gilde</de>
    <en>Balmora, Morag Tong Guild</en>
  </cell>
  <cell>
    <de>Balmora, Nalcarya von Weißhafen: Alchemistin</de>
    <en>Balmora, Nalcarya of White Haven: Fine Alchemist</en>
  </cell>
  <cell>
    <de>Balmora, Neunzehs Haus</de>
    <en>Balmora, Nine Toes' House</en>
  </cell>
  <cell>
    <de>Balmora, Ra'Virr: Händler</de>
    <en>Balmora, Ra'Virr: Trader</en>
  </cell>
  <cell>
    <de>Balmora, Rarayn Radarys Haus</de>
    <en>Balmora, Rarayn Radarys' House</en>
  </cell>
  <cell>
    <de>Balmora, Ratstaverne</de>
  </cell>
  <cell>
    <de>Balmora, Rithleens Haus</de>
    <en>Balmora, Rithleen's House</en>
  </cell>
  <cell>
    <de>Balmora, Südwall-Taverne</de>
    <en>Balmora, South Wall Cornerclub</en>
  </cell>
  <cell>
    <de>Balmora, Tempel</de>
    <en>Balmora, Temple</en>
  </cell>
  <cell>
    <de>Balmora, Tsiyas Haus</de>
    <en>Balmora, Tsiya's House</en>
  </cell>
  <cell>
    <de>Balmora, Tyermaillins Haus</de>
    <en>Balmora, Tyermaillin's House</en>
  </cell>
  <cell>
    <de>Balmora, Vorar Helas Haus</de>
    <en>Balmora, Vorar Helas' House</en>
  </cell>
  <cell>
    <de>Balmora, Voris Haus</de>
    <en>Balmora, Vori's House</en>
  </cell>
  <cell>
    <de>Balmora, Westlicher Wachturm, Nord</de>
    <en>Balmora, Western Guard Tower North</en>
  </cell>
  <cell>
    <de>Balmora, Westlicher Wachturm, Süd</de>
    <en>Balmora, Western Guard Tower South</en>
  </cell>
  <cell>
    <de>Balmora, Zum Glückspilz</de>
  </cell>
  <cell>
    <de>Balmora, Östlicher Wachturm</de>
  </cell>
  <cell>
    <de>Balurs Bauernhaus</de>
    <en>Balur's Farmhouse</en>
  </cell>
  <cell>
    <de>Bamz-Amschend, Halle des Herdfeuers</de>
    <en>Bamz-Amschend, Hearthfire Hall</en>
  </cell>
  <cell>
    <de>Bamz-Amschend, Halle des Heulens</de>
    <en>Bamz-Amschend, Hall of Wails</en>
  </cell>
  <cell>
    <de>Bamz-Amschend, Halle des Windes</de>
    <en>Bamz-Amschend, Hall of Winds</en>
  </cell>
  <cell>
    <de>Bamz-Amschend, Himmelsspalt-Galerie</de>
    <en>Bamz-Amschend, Skybreak Gallery</en>
  </cell>
  <cell>
    <de>Bamz-Amschend, Königsgang</de>
    <en>Bamz-Amschend, King's Walk</en>
  </cell>
  <cell>
    <de>Bamz-Amschend, Passage des Flüsterns</de>
    <en>Bamz-Amschend, Passage of Whispers</en>
  </cell>
  <cell>
    <de>Bamz-Amschend, Passage des Wandernden</de>
    <en>Bamz-Amschend, Passage of the Walker</en>
  </cell>
  <cell>
    <de>Bamz-Amschend, Radacs Schmiede</de>
    <en>Bamz-Amschend, Radac's Forge</en>
  </cell>
  <cell>
    <de>Band, Eiermine</de>
    <en>Band Egg Mine</en>
  </cell>
  <cell>
    <de>Bensamsi</de>
    <en>Bensamsi</en>
  </cell>
  <cell>
    <de>Bensiberib-Lager, Odaishahs Zelt</de>
    <en>Bensiberib Camp, Odaishah's Yurt</en>
  </cell>
  <cell>
    <de>Beram-Ahnengruft</de>
  </cell>
  <cell>
    <de>Beran-Ahnengruft</de>
    <en>Beran Ancestral Tomb</en>
  </cell>
  <cell>
    <de>Berandas</de>
    <en>Berandas</en>
  </cell>
  <cell>
    <de>Berandas, Festung, Oberste Ebene</de>
    <en>Berandas, Keep, Top Level</en>
  </cell>
  <cell>
    <de>Berandas, Festung, Unterste Ebene</de>
    <en>Berandas, Keep, Bottom Level</en>
  </cell>
  <cell>
    <de>Berandas, Propylon-Kammer</de>
    <en>Berandas, Propylon Chamber</en>
  </cell>
  <cell>
    <de>Berandas, Untergrund</de>
    <en>Berandas, Underground</en>
  </cell>
  <cell>
    <de>Beshara</de>
    <en>Beshara</en>
  </cell>
  <cell>
    <de>Bthanchend</de>
    <en>Bthanchend</en>
  </cell>
  <cell>
    <de>Bthuand</de>
    <en>Bthuand</en>
  </cell>
  <cell>
    <de>Bthungthumz</de>
    <en>Bthungthumz</en>
  </cell>
  <cell>
    <de>Caldera</de>
    <en>Caldera</en>
  </cell>
  <cell>
    <de>Caldera, Bashuk gra-Bats Haus</de>
    <en>Caldera, Bashuk gra-Bat's House</en>
  </cell>
  <cell>
    <de>Caldera, Canodia Felannus' Haus</de>
    <en>Caldera, Canodia Felannus' House</en>
  </cell>
  <cell>
    <de>Caldera, Dro'Shavirs Haus</de>
    <en>Caldera, Dro'Shavir's House</en>
  </cell>
  <cell>
    <de>Caldera, Elmussa Damoris Haus</de>
    <en>Caldera, Elmussa Damori's House</en>
  </cell>
  <cell>
    <de>Caldera, Erste Sklavenhütte</de>
    <en>Caldera, Slave Shack One</en>
  </cell>
  <cell>
    <de>Caldera, Falanaamo: Schneider</de>
    <en>Caldera, Falanaamo: Clothier</en>
  </cell>
  <cell>
    <de>Caldera, Halle des Regenten</de>
    <en>Caldera, Governor's Hall</en>
  </cell>
  <cell>
    <de>Caldera, Haus Ghorak</de>
    <en>Caldera, Ghorak Manor</en>
  </cell>
  <cell>
    <de>Caldera, Hodlismod: Waffenschmied</de>
    <en>Caldera, Hodlismod: Armorer</en>
  </cell>
  <cell>
    <de>Caldera, Irgola: Pfandleiher</de>
    <en>Caldera, Irgola: Pawnbroker</en>
  </cell>
  <cell>
    <de>Caldera, Keel-Raniurs Haus</de>
    <en>Caldera, Keel-Raniur's House</en>
  </cell>
  <cell>
    <de>Caldera, Magiergilde</de>
    <en>Caldera, Guild of Mages</en>
  </cell>
  <cell>
    <de>Caldera, Minen, Schreibstube</de>
  </cell>
  <cell>
    <de>Caldera, Minen, Unterkünfte</de>
  </cell>
  <cell>
    <de>Caldera, Nedhelas' Haus</de>
    <en>Caldera, Nedhelas' House</en>
  </cell>
  <cell>
    <de>Caldera, Nördliche Wachtürme</de>
    <en>Caldera, North Guard Towers</en>
  </cell>
  <cell>
    <de>Caldera, Odairan Ashummi-Ammus' Haus</de>
    <en>Caldera, Odairan Ashummi-Ammus' House</en>
  </cell>
  <cell>
    <de>Caldera, Shenks Hütte</de>
    <en>Caldera, Shenk's Shovel</en>
  </cell>
  <cell>
    <de>Caldera, Surane Leorianes Haus</de>
    <en>Caldera, Surane Leoriane's House</en>
  </cell>
  <cell>
    <de>Caldera, Südliche Wachtürme</de>
    <en>Caldera, South Guard Towers</en>
  </cell>
  <cell>
    <de>Caldera, Valvius Mevureius Haus</de>
    <en>Caldera, Valvius Mevureius' House</en>
  </cell>
  <cell>
    <de>Caldera, Verick Gemain: Händler</de>
    <en>Caldera, Verick Gemain: Trader</en>
  </cell>
  <cell>
    <de>Caldera, Wachturm der Mine</de>
  </cell>
  <cell>
    <de>Caldera, Zweite Sklavenhütte</de>
    <en>Caldera, Slave Shack Two</en>
  </cell>
  <cell>
    <de>Caldera-Mine</de>
    <en>Caldera Mine</en>
  </cell>
  <cell>
    <de>Chun-Ook, Kabine</de>
    <en>Chun-Ook, Cabin</en>
  </cell>
  <cell>
    <de>Chun-Ook, Oberdeck</de>
    <en>Chun-Ook, Upper Level</en>
  </cell>
  <cell>
    <de>Chun-Ook, Unterdeck</de>
    <en>Chun-Ook, Lower Level</en>
  </cell>
  <cell>
    <de>Corprusarium</de>
    <en>Corprusarium</en>
  </cell>
  <cell>
    <de>Dagon Fel</de>
    <en>Dagon Fel</en>
  </cell>
  <cell>
    <de>Dagon Fel, Andre Maahuls Turm</de>
    <en>Dagon Fel, Andre Maul's Tower</en>
  </cell>
  <cell>
    <de>Dagon Fel, Anjah Segelschwinges Haus</de>
    <en>Dagon Fel, Anja Swift-Sailer's House</en>
  </cell>
  <cell>
    <de>Dagon Fel, Das Ende der Welt</de>
  </cell>
  <cell>
    <de>Dagon Fel, Fanar Forkbards Haus</de>
    <en>Dagon Fel, Fanar Fork-Beard's House</en>
  </cell>
  <cell>
    <de>Dagon Fel, Fjorrods Haus</de>
    <en>Dagon Fel, Fjorrod's House</en>
  </cell>
  <cell>
    <de>Dagon Fel, Gasthaus Zum Ende der Welt</de>
  </cell>
  <cell>
    <de>Dagon Fel, Greidil Halbtrolls Haus</de>
    <en>Dagon Fel, Greidil Half-Troll's House</en>
  </cell>
  <cell>
    <de>Dagon Fel, Haus von Itar dem Sanftmütigen</de>
    <en>Dagon Fel, Itar the Gentle's House</en>
  </cell>
  <cell>
    <de>Dagon Fel, Heifnir: Händler</de>
    <en>Dagon Fel, Heifnir: Trader</en>
  </cell>
  <cell>
    <de>Dagon Fel, Hurgs Haus</de>
    <en>Dagon Fel, Hurg's House</en>
  </cell>
  <cell>
    <de>Dagon Fel, Leer stehender Turm</de>
    <en>Dagon Fel, Vacant Tower</en>
  </cell>
  <cell>
    <de>Dagon Fel, Mettes Haus</de>
    <en>Dagon Fel, Mette's House</en>
  </cell>
  <cell>
    <de>Dagon Fel, Onmi Hartmunds Haus</de>
    <en>Dagon Fel, Onmi Hard-mouth's House</en>
  </cell>
  <cell>
    <de>Dagon Fel, Sorkvilds Turm</de>
    <en>Dagon Fel, Sorkvild's Tower</en>
  </cell>
  <cell>